name: Ghost Player
main: com.skyost.gp.GhostPlayerPlugin
description: Be ghooooooooost !
version: 0.5
author: Skyost
website: http://www.imc-bans.eu/
commands:
 ghostview:
  aliases: gv
  description: /ghostview
 ghost:
  aliases: g
  description: /ghost
 silentghost:
  aliases: sg
  description: /silentghost
 removeghost:
  aliases: rg
  description: /removeghost <player>
 clearsghosts:
  aliases: cg
  description: /clearsghosts
 human:
  aliases: h
  description: /human
 silenthuman:
  aliases: sh
  description: /silenthuman
permisions:
 ghostplayer.player.ghostview:
  default: true
  description: Allow you to view a block like a ghost !
 ghostplayer.player.beghost:
  default: true
  description: Allow you to be a ghost !
 ghostplayer.player.behuman:
  default: true
  description: Allow you to be an human !
 ghostplayer.admin.removeghost:
  default: op
  description: Allow you to remove a player from the ghosts !
 ghostplayer.admin.clearsghosts:
  default: op
  description: Allow you to clears all ghosts !
